src/Entity/Contract.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Entity;

use App\ActivityMonitor\MonitorableEntityInterface;
use App\ActivityMonitor\MonitorableEntityTrait;
use App\Repository\ContractRepository;
use App\Uid\UidEntityInterface;
use App\Uid\UidEntityTrait;
use App\Utils;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Translation\TranslatableMessage;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ContractRepository::class)]
class Contract implements EntityInterface, MonitorableEntityInterface, UidEntityInterface
{
    use MonitorableEntityTrait;
    use UidEntityTrait;

    public const NAME_MAX_LENGTH = 255;
    public const STATUSES = ['coming', 'ongoing', 'finished'];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $uid = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $createdBy = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $updatedBy = null;

    #[ORM\Column(length: self::NAME_MAX_LENGTH)]
    #[Assert\NotBlank(
        message: new TranslatableMessage('contract.name.required', [], 'errors'),
    )]
    #[Assert\Length(
        max: self::NAME_MAX_LENGTH,
        maxMessage: new TranslatableMessage('contract.name.max_chars', [], 'errors'),
    )]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Assert\NotBlank(
        message: new TranslatableMessage('contract.start_at.required', [], 'errors'),
    )]
    private ?\DateTimeImmutable $startAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    #[Assert\NotBlank(
        message: new TranslatableMessage('contract.end_at.required', [], 'errors'),
    )]
    #[Assert\GreaterThan(
        propertyPath: 'startAt',
        message: new TranslatableMessage('contract.end_at.greater_than_start_at', [], 'errors'),
    )]
    private ?\DateTimeImmutable $endAt = null;

    #[ORM\Column]
    #[Assert\NotBlank(
        message: new TranslatableMessage('contract.max_hours.required', [], 'errors'),
    )]
    #[Assert\GreaterThan(
        value: 0,
        message: new TranslatableMessage('contract.max_hours.greater_than_zero', [], 'errors'),
    )]
    private ?int $maxHours = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $notes = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?Organization $organization = null;

    /** @var Collection<int, Ticket> $tickets */
    #[ORM\ManyToMany(targetEntity: Ticket::class, mappedBy: 'contracts')]
    private Collection $tickets;

    /** @var Collection<int, TimeSpent> $timeSpents */
    #[ORM\OneToMany(mappedBy: 'contract', targetEntity: TimeSpent::class)]
    private Collection $timeSpents;

    #[ORM\Column(options: ["default" => 0])]
    private ?int $timeAccountingUnit = null;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $hoursAlert = null;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $dateAlert = null;

    #[ORM\OneToOne(targetEntity: self::class)]
    private ?self $renewedBy = null;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
        $this->timeSpents = new ArrayCollection();
        $this->name = '';
        $this->maxHours = 10;
        $this->startAt = Utils\Time::now();
        $this->endAt = Utils\Time::relative('last day of december');
        $this->timeAccountingUnit = 30;
        $this->notes = '';
        $this->hoursAlert = 0;
        $this->dateAlert = 0;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getRenewedName(): ?string
    {
        if (preg_match('/\d$/', $this->name) === 1) {
            $name = $this->name;
            return strval(++$name);
        } else {
            return $this->name;
        }
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStartAt(): ?\DateTimeImmutable
    {
        return $this->startAt;
    }

    public function setStartAt(\DateTimeImmutable $startAt): static
    {
        $this->startAt = $startAt->modify('00:00:00');

        return $this;
    }

    public function getEndAt(): ?\DateTimeImmutable
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeImmutable $endAt): static
    {
        $this->endAt = $endAt->modify('23:59:59');

        return $this;
    }

    public function getMaxHours(): ?int
    {
        return $this->maxHours;
    }

    public function setMaxHours(int $maxHours): static
    {
        $this->maxHours = $maxHours;

        return $this;
    }

    public function getConsumedMinutes(): int
    {
        $times = array_map(function (TimeSpent $timeSpent): int {
            return $timeSpent->getTime();
        }, $this->getTimeSpents()->getValues());

        $consumedHours = array_sum($times);

        return $consumedHours;
    }

    public function getConsumedHours(): float
    {
        return $this->getConsumedMinutes() / 60;
    }

    public function getConsumedPercentage(): float
    {
        $consumedHours = $this->getConsumedHours();
        $maxHours = $this->getMaxHours();
        return $consumedHours / $maxHours;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getOrganization(): ?Organization
    {
        return $this->organization;
    }

    public function setOrganization(?Organization $organization): static
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * @return value-of<self::STATUSES>
     */
    public function getStatus(): string
    {
        $today = Utils\Time::now();
        if ($today < $this->startAt) {
            return 'coming';
        } elseif ($today < $this->endAt) {
            return 'ongoing';
        } else {
            return 'finished';
        }
    }

    public function getStatusLabel(): string
    {
        $statusesWithLabels = self::getStatusesWithLabels();
        return $statusesWithLabels[$this->getStatus()];
    }

    public function getStatusBadgeColor(): string
    {
        $status = $this->getStatus();
        if ($status === 'coming') {
            return 'blue';
        } elseif ($status === 'ongoing') {
            return 'green';
        } elseif ($status === 'finished') {
            return 'grey';
        }
    }

    /**
     * @return array<value-of<self::STATUSES>, string>
     */
    public static function getStatusesWithLabels(): array
    {
        return [
            'coming' => new TranslatableMessage('contracts.status.coming'),
            'ongoing' => new TranslatableMessage('contracts.status.ongoing'),
            'finished' => new TranslatableMessage('contracts.status.finished'),
        ];
    }

    /**
     * Return the number of days between startAt and endAt.
     */
    public function getDaysDuration(): int
    {
        $interval = $this->startAt->diff($this->endAt);
        // We add a day because e.g. 2023-01-01 00:00:00 to 2023-01-01 23:59:59
        // will return 0 day, while we consider on our side that a whole day
        // passed.
        return intval($interval->format('%a')) + 1;
    }

    /**
     * Return the number of days since startAt. It returns 0 if startAt is in
     * the future, or the contract duration if endAt is in the past.
     */
    public function getDaysProgress(): int
    {
        $now = Utils\Time::now();
        if ($now < $this->startAt) {
            return 0;
        }

        if ($now >= $this->endAt) {
            return $this->getDaysDuration();
        }

        $interval = $this->startAt->diff($now);
        return intval($interval->format('%a'));
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    /**
     * @return Collection<int, TimeSpent>
     */
    public function getTimeSpents(): Collection
    {
        return $this->timeSpents;
    }

    public function addTimeSpent(TimeSpent $timeSpent): static
    {
        if (!$this->timeSpents->contains($timeSpent)) {
            $this->timeSpents->add($timeSpent);
            $timeSpent->setContract($this);
        }

        return $this;
    }

    public function removeTimeSpent(TimeSpent $timeSpent): static
    {
        if ($this->timeSpents->removeElement($timeSpent)) {
            // set the owning side to null (unless already changed)
            if ($timeSpent->getContract() === $this) {
                $timeSpent->setContract(null);
            }
        }

        return $this;
    }

    public function getTimeAccountingUnit(): ?int
    {
        return $this->timeAccountingUnit;
    }

    public function setTimeAccountingUnit(int $timeAccountingUnit): static
    {
        $this->timeAccountingUnit = $timeAccountingUnit;

        return $this;
    }

    public function initDefaultAlerts(): void
    {
        $this->hoursAlert = 80;
        $daysDuration = $this->getDaysDuration();
        $this->dateAlert = intval(round($daysDuration * 0.2));
    }

    public function getHoursAlert(): ?int
    {
        return $this->hoursAlert;
    }

    public function getHoursOfAlert(): ?float
    {

src/Controller/Contracts/AlertsController.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Controller\Contracts;

use App\Controller\BaseController;
use App\Entity\Contract;
use App\Repository\ContractRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class AlertsController extends BaseController
{
    #[Route('/contracts/{uid:contract}/alerts/edit', name: 'edit contract alerts', methods: ['GET', 'HEAD'])]
    public function edit(
        Contract $contract,
    ): Response {
        $organization = $contract->getOrganization();

        $this->denyAccessUnlessGranted('orga:manage:contracts', $organization);

        return $this->render('contracts/alerts/edit.html.twig', [
            'organization' => $organization,
            'contract' => $contract,
            'hoursAlert' => $contract->getHoursAlert(),
            'dateAlert' => $contract->getDateAlert(),
        ]);
    }

    #[Route('/contracts/{uid:contract}/alerts/edit', name: 'update contract alerts', methods: ['POST'])]
    public function update(
        Contract $contract,
        Request $request,
        ContractRepository $contractRepository,
        TranslatorInterface $translator,
    ): Response {
        $organization = $contract->getOrganization();

        $this->denyAccessUnlessGranted('orga:manage:contracts', $organization);

        $hoursAlert = $request->request->getInt('hoursAlert');
        $dateAlert = $request->request->getInt('dateAlert');
        $csrfToken = $request->request->getString('_csrf_token');

        if ($hoursAlert < 0) {
            $hoursAlert = 0;
        } elseif ($hoursAlert > 100) {
            $hoursAlert = 100;
        }

        if ($dateAlert < 0) {
            $dateAlert = 0;
        } elseif ($dateAlert > $contract->getDaysDuration()) {
            $dateAlert = $contract->getDaysDuration();
        }

        if (!$this->isCsrfTokenValid('update contract alerts', $csrfToken)) {
            return $this->renderBadRequest('contracts/alerts/edit.html.twig', [
                'organization' => $organization,
                'contract' => $contract,
                'hoursAlert' => $hoursAlert,
                'dateAlert' => $dateAlert,
                'error' => $translator->trans('csrf.invalid', [], 'errors'),
            ]);
        }

        $contract->setHoursAlert($hoursAlert);
        $contract->setDateAlert($dateAlert);

        $contractRepository->save($contract, true);

        return $this->redirectToRoute('contract', [
            'uid' => $contract->getUid(),
        ]);
    }
}

src/Controller/Contracts/MaxHoursController.php
<?php

// This file is part of Bileto.
// Copyright 2022-2024 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Controller\Contracts;

use App\Controller\BaseController;
use App\Entity\Contract;
use App\Repository\ContractRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class MaxHoursController extends BaseController
{
    #[Route('/contracts/{uid}/max-hours/edit', name: 'edit contract max hours', methods: ['GET', 'HEAD'])]
    public function edit(
        Contract $contract,
    ): Response {
        $organization = $contract->getOrganization();

        $this->denyAccessUnlessGranted('orga:manage:contracts', $organization);

        return $this->render('contracts/max_hours/edit.html.twig', [
            'organization' => $organization,
            'contract' => $contract,
            'additionalHours' => 0,
        ]);
    }

    #[Route('/contracts/{uid}/max-hours/edit', name: 'update contract max hours', methods: ['POST'])]
    public function update(
        Contract $contract,
        Request $request,
        ContractRepository $contractRepository,
        TranslatorInterface $translator,
    ): Response {
        $organization = $contract->getOrganization();

        $this->denyAccessUnlessGranted('orga:manage:contracts', $organization);

        $additionalHours = $request->request->getInt('additionalHours');
        $csrfToken = $request->request->getString('_csrf_token');

        if ($additionalHours < 0) {
            $additionalHours = 0;
        }

        if (!$this->isCsrfTokenValid('update contract max hours', $csrfToken)) {
            return $this->renderBadRequest('contracts/max_hours/edit.html.twig', [
                'organization' => $organization,
                'contract' => $contract,
                'additionalHours' => $additionalHours,
                'error' => $translator->trans('csrf.invalid', [], 'errors'),
            ]);
        }

        $maxHours = $contract->getMaxHours() + $additionalHours;
        $contract->setMaxHours($maxHours);

        $contractRepository->save($contract, true);

        return $this->redirectToRoute('organization contract', [
            'uid' => $organization->getUid(),
            'contract_uid' => $contract->getUid(),
        ]);
    }
}

src/Controller/Tickets/ContractsController.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Controller\Tickets;

use App\Controller\BaseController;
use App\Entity;
use App\Form;
use App\Repository;
use App\Service;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ContractsController extends BaseController
{
    #[Route('/tickets/{uid:ticket}/contracts/edit', name: 'edit ticket contracts')]
    public function edit(
        Entity\Ticket $ticket,
        Request $request,
        Repository\TicketRepository $ticketRepository,
        Repository\TimeSpentRepository $timeSpentRepository,
        Service\ContractTimeAccounting $contractTimeAccounting,
    ): Response {
        $this->denyAccessUnlessGranted('orga:update:tickets:contracts', $ticket);
        $this->denyAccessIfTicketIsClosed($ticket);

        $form = $this->createNamedForm('ticket_ongoing_contract', Form\Ticket\OngoingContractForm::class, $ticket);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ticket = $form->getData();
            $ticketRepository->save($ticket, true);

            $ongoingContract = $form->get('ongoingContract')->getData();
            $includeUnaccountedTime = $form->get('includeUnaccountedTime')->getData();

            if ($includeUnaccountedTime && $ongoingContract) {
                $timeSpents = $ticket->getUnaccountedTimeSpents()->getValues();
                $contractTimeAccounting->accountTimeSpents($ongoingContract, $timeSpents);
                $timeSpentRepository->save($timeSpents, true);
            }

            return $this->redirectToRoute('ticket', [
                'uid' => $ticket->getUid(),
            ]);
        }

        return $this->render('tickets/contracts/edit.html.twig', [
            'ticket' => $ticket,
            'form' => $form,
        ]);
    }
}

templates/contracts/_form.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.name) }}

    <div class="cols flow">
        <div class="col--extend">
            {{ form_row(form.startAt) }}
        </div>

        <div class="col--extend">
            {{ form_row(form.endAt) }}
        </div>
    </div>

    {{ form_row(form.maxHours) }}

    {{ form_row(form.timeAccountingUnit) }}

    {{ form_row(form.notes) }}

    {% if form.associateTickets is defined %}
        {{ form_row(form.associateTickets) }}
    {% endif %}

    {% if form.associateUnaccountedTimes is defined %}
        {{ form_row(form.associateUnaccountedTimes) }}
    {% endif %}
{{ form_end(form) }}

templates/contracts/_list.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

<ul class="list--padded list--border list--nostyle">
    {% for contract in contracts %}
        <li class="cols flow flow--larger" data-test="contract-item">
            <div class="col--size6 flow flow--small">
                <h2 class="list__item-title">
                    <a href="{{ path('contract', {'uid': contract.uid }) }}">
                        {{ contract.name }}
                    </a>
                </h2>

                <p class="text--small">
                    <time datetime="{{ contract.startAt | dateIso }}">
                        {{ contract.startAt | dateTrans('dd MMM yyyy') }}
                    </time>

                    —

                    <time datetime="{{ contract.endAt | dateIso }}">
                        {{ contract.endAt | dateTrans('dd MMM yyyy') }}
                    </time>

                    {% if contract.renewedBy %}
                        ({{ 'contracts.index.renewed' | trans }})
                    {% endif %}
                </p>
            </div>

            <div class="col--size4 flow flow--small text--primary-dark">
                <p>
                    <a class="list-contracts__organization" href="{{ path('organization contracts', { uid: contract.organization.uid }) }}">
                        {{ contract.organization.name }}
                    </a>
                </p>

                <p>
                    <a href="{{ path('organization tickets', { uid: contract.organization.uid, q: 'contract:#' ~ contract.id }) }}">
                        {{ 'contracts.index.tickets' | trans({ count: contract.tickets.count }) }}
                    </a>
                </p>

                <p>
                    {{ 'contracts.hours_consumed' | trans({
                        'hours': contract.consumedMinutes | formatMinutes,
                        'maxHours': contract.maxHours,
                        'percentage': contract.consumedPercentage,
                    }) | raw }}
                </p>
            </div>

            <div class="col--size2 flow flow--small">
                <div class="badge badge--block badge--{{ contract.statusBadgeColor }}" title="{{ 'contracts.status' | trans }}">
                    <span class="sr-only">
                        {{ 'contracts.status' | trans }}
                    </span>

                    {{ contract.statusLabel | trans }}
                </div>

                {% if contract.alertActivated %}
                    <div class="badge badge--block badge--orange">
                        {{ icon('triangle-exclamation-warning') }}
                        {{ 'contracts.index.alert' | trans }}
                    </div>
                {% endif %}
            </div>
        </li>
    {% endfor %}
</ul>

templates/contracts/_search_form.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

<div class="panel flow flow--large">
    <h2>
        {{ 'forms.search.advanced_title' | trans }}
    </h2>

    {{ form_start(advancedSearchForm) }}
        {{ form_errors(advancedSearchForm) }}

        {{ form_row(advancedSearchForm.q) }}

        <button
            class="button--anchor text--small"
            data-controller="modal-opener"
            data-action="modal-opener#fetch"
            data-modal-opener-selector-value="{{ path('advanced search syntax', { subject: 'contracts' }) }}"
        >
            {{ 'forms.search.advanced_help' | trans }}
        </button>

        <div class="text--right">
            <button class="button--animated-icon" type="submit">
                {{ 'forms.search.submit' | trans }}
                {{ icon('arrow-right') }}
            </button>
        </div>
    {{ form_end(advancedSearchForm) }}
</div>

templates/contracts/show.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'organization.html.twig' %}

{% set currentMenu = 'contracts' %}

{% block title %}{{ contract.name }} – {{ organization.name }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('organizations') }}">
            {{ 'organizations.index.title' | trans }}
        </a>

        <a href="{{ path('organization', { uid: organization.uid }) }}">
            {{ organization.name }}
        </a>

        <a href="{{ path('organization contracts', { uid: organization.uid }) }}">
            {{ 'contracts.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ contract.name }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <div class="flow flow--smaller">
            <div class="cols cols--center text--center flow flow--small">
                <h1>
                    {{ contract.name }}
                </h1>

                <span class="badge badge--{{ contract.statusBadgeColor }}" title="{{ 'contracts.status' | trans }}">
                    <span class="sr-only">
                        {{ 'contracts.status' | trans }}
                    </span>

                    {{ contract.statusLabel | trans }}
                </span>
            </div>

            {% if contract.renewedBy %}
                <p class="text--center">
                    {{ 'contracts.show.renewed_by' | trans }}

                    <a href="{{ path('contract', { uid: contract.renewedBy.uid }) }} ">
                        {{ contract.renewedBy.name }}
                    </a>
                </p>
            {% endif %}

            {% if is_granted('orga:manage:contracts', organization) %}
                <div class="text--right">
                    <details
                        class="popup"
                        data-controller="popup"
                        data-action="toggle->popup#update click@window->popup#closeOnClickOutside"
                    >
                        <summary class="popup__opener">
                            <span class="button button--discreet">
                                {{ 'common.actions' | trans }}
                                {{ icon('angle-down') }}
                            </span>
                        </summary>

                        <nav class="popup__container popup__container--right">
                            <button
                                class="popup__item"
                                data-controller="modal-opener"
                                data-action="modal-opener#fetch"
                                data-modal-opener-selector-value="{{ path('edit contract alerts', { uid: contract.uid }) }}"
                            >
                                {{ 'contracts.show.set_up_alerts' | trans }}
                            </button>

                            <a class="popup__item" href="{{ path('edit contract', { uid: contract.uid }) }}">
                                {{ 'contracts.show.edit' | trans }}
                            </a>

                            {% if not contract.renewedBy %}
                                <a class="popup__item" href="{{ path('new organization contract', { uid: organization.uid, from: contract.uid }) }}">
                                    {{ 'contracts.show.renew' | trans }}
                                </a>
                            {% endif %}
                        </nav>
                    </details>
                </div>
            {% endif %}
        </div>

        <div class="panel">
            <div class="wrapper wrapper--small wrapper--center flow flow--larger">
                {% if contract.timeAccountingUnit %}
                    <p>
                        {{ 'contracts.show.time_accounting_unit' | trans({ count: contract.timeAccountingUnit }) }}
                    </p>
                {% endif %}

                <div class="flow flow--small">
                    <div class="text--small" id="contract-hours-consumed">
                        {% if contract.hoursAlertActivated %}
                            <span>
                                {{ icon('triangle-exclamation-warning') }}
                                <span class="sr-only">
                                    {{ 'contracts.show.warning' | trans }}
                                </span>
                            </span>
                        {% endif %}

                        {{ 'contracts.hours_consumed' | trans({
                            'hours': contract.consumedMinutes | formatMinutes,
                            'maxHours': contract.maxHours,
                            'percentage': contract.consumedPercentage,
                        }) | raw }}
                    </div>

                    <div class="progress-with-marker">
                        <progress
                            value="{{ contract.consumedHours }}"
                            max="{{ contract.maxHours }}"
                            class="{{ contract.hoursAlertActivated ? 'progress--warning' }}"
                            aria-labelledby="contract-hours-consumed"
                        >
                        </progress>

                        {% if contract.hoursAlert > 0 %}
                            <div class="progress__marker" style="--marker-percent: {{ contract.hoursAlert }}%;">
                                <span class="sr-only">
                                    {{ 'contracts.show.alert' | trans }}
                                </span>

                                {{ contract.hoursOfAlert | formatHours }}
                            </div>
                        {% endif %}
                    </div>
                </div>

                <div class="flow flow--small">
                    <div class="cols cols--center cols--always flow text--small">
                        <div class="col--extend" id="contract-days-consumed">
                            {% if contract.dateAlertActivated %}
                                <span>
                                    {{ icon('triangle-exclamation-warning') }}
                                    <span class="sr-only">
                                        {{ 'contracts.show.warning' | trans }}
                                    </span>
                                </span>
                            {% endif %}

                            {{ 'contracts.days_consumed' | trans({ 'days': contract.daysProgress }) | raw }}
                        </div>

                        <div class="text--secondary">
                            <time datetime="{{ contract.startAt | dateIso }}">
                                {{ contract.startAt | dateTrans('dd MMM yyyy') }}
                            </time>

                            —

                            <time datetime="{{ contract.endAt | dateIso }}">
                                {{ contract.endAt | dateTrans('dd MMM yyyy') }}
                            </time>
                        </div>
                    </div>

                    <div class="progress-with-marker">
                        <progress
                            value="{{ contract.daysProgress }}"
                            max="{{ contract.daysDuration }}"
                            class="{{ contract.dateAlertActivated ? 'progress--warning' }}"
                            aria-labelledby="contract-days-consumed"
                        >
                        </progress>

                        {% if contract.dateAlert > 0 %}
                            <div class="progress__marker" style="--marker-percent: {{ contract.dateAlertPercent }}%;">
                                <span class="sr-only">
                                    {{ 'contracts.show.alert' | trans }}
                                </span>

                                <time datetime="{{ contract.dateOfAlert | dateIso }}" title="{{ contract.dateOfAlert | dateTrans('dd MMM yyyy') }}">
                                    {{ 'contracts.show.alert.before_end' | trans({ days: contract.dateAlert }) | raw }}
                                </time>
                            </div>
                        {% endif %}
                    </div>
                </div>

                {% if contract.notes and is_granted('orga:see:contracts:notes', organization) %}
                    <article class="message message--confidential">
                        <div class="message__box">
                            <div class="message__top">
                                <h2>
                                    {{ 'contracts.notes' | trans }}
                                </h2>

                                <div class="badge badge--red">
                                    {{ icon('shield-halved') }}
                                    {{ 'contracts.show.notes_confidential' | trans }}
                                </div>
                            </div>

                            <p class="message__content">
                                {{ contract.notes | nl2br }}
                            </p>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}