src/Entity/MailboxEmail.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Entity;

use App\ActivityMonitor\MonitorableEntityInterface;
use App\ActivityMonitor\MonitorableEntityTrait;
use App\Repository\MailboxEmailRepository;
use App\Service;
use App\Uid\UidEntityInterface;
use App\Uid\UidEntityTrait;
use App\Utils\Time;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Webklex\PHPIMAP;

#[ORM\Entity(repositoryClass: MailboxEmailRepository::class)]
class MailboxEmail implements EntityInterface, MonitorableEntityInterface, UidEntityInterface
{
    use MonitorableEntityTrait;
    use UidEntityTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20, unique: true)]
    private ?string $uid = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $createdBy = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $updatedBy = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $raw = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private ?Mailbox $mailbox = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $lastError = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $lastErrorAt = null;

    private ?PHPIMAP\Message $email = null;

    public function __construct(Mailbox $mailbox, PHPIMAP\Message $email)
    {
        $this->mailbox = $mailbox;
        $this->raw = $email->getHeader()->raw . "\r\n\r\n" . $email->getRawBody();
        $this->lastError = '';
    }

    public function getRaw(): ?string
    {
        return $this->raw;
    }

    public function setRaw(string $raw): self
    {
        $this->raw = $raw;

        return $this;
    }

    public function getMailbox(): ?Mailbox
    {
        return $this->mailbox;
    }

    public function setMailbox(?Mailbox $mailbox): self
    {
        $this->mailbox = $mailbox;

        return $this;
    }

    public function getLastError(): ?string
    {
        return $this->lastError;
    }

    public function getLastErrorSummary(): string
    {
        if (!$this->lastError) {
            return '';
        }

        $splitError = explode("\n", trim($this->lastError));
        return $splitError[0];
    }

    public function setLastError(string $lastError): self
    {
        $this->lastError = $lastError;
        $this->lastErrorAt = Time::now();

        return $this;
    }

    public function getLastErrorAt(): ?\DateTimeImmutable
    {
        return $this->lastErrorAt;
    }

    public function getEmail(): PHPIMAP\Message
    {
        if (!$this->email) {
            $config = Service\MailboxService::getConfig();
            $this->email = PHPIMAP\Message::fromString($this->raw, $config);
        }

        return $this->email;
    }

    public function getMessageId(): string
    {
        return $this->getEmail()->getMessageId()->first();
    }

    public function getFrom(): string
    {
        return $this->getEmail()->getFrom()->first()->mail;
    }

    /**
     * @return string[]
     */
    public function getTo(): array
    {
        $email = $this->getEmail();
        $ccAddresses = $email->getTo()->all();

        return array_map(function (PHPIMAP\Address $address): string {
            return $address->mail;
        }, $ccAddresses);
    }

    /**
     * @return string[]
     */
    public function getCc(): array
    {
        $email = $this->getEmail();
        $ccAddresses = $email->getCc()->all();

        return array_map(function (PHPIMAP\Address $address): string {
            return $address->mail;
        }, $ccAddresses);
    }

    public function getInReplyTo(): ?string
    {
        $inReplyTo = $this->getEmail()->getInReplyTo()->first();
        $inReplyTo = str_replace(['<', '>'], '', $inReplyTo);

        if (!$inReplyTo) {
            return null;
        }

        return $inReplyTo;
    }

    /**
     * Return whether the email is an autoreply or not.
     *
     * Detecting such a thing is tricky. RFC 3834 specifies how it should be
     * done, in particular by using the "Auto-Submitted" header. However, many
     * mail providers don't care, so we're left with some rules learnt from the
     * experience of others.
     *
     * Some references that helped to build this method:
     *
     * - RFC 3834: https://datatracker.ietf.org/doc/html/rfc3834
     * - FreeScout code: https://github.com/freescout-help-desk/freescout/blob/1.8.203/app/Misc/Mail.php#L646
     * - Stackoverflow answer: https://stackoverflow.com/a/14320010
     * - Blog post by arp242: https://www.arp242.net/autoreply.html
     * - Blog post on jitbit.com: https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/
     * - Wiki of multi_mail Ruby gem: https://github.com/jpmckinney/multi_mail/wiki/Detecting-autoresponders
     *
     * Note that we don't use all of the techniques listed in these references.
     * In particular, we don't want detecting autoreplies based on the subject
     * prefix (e.g. "Auto:") because this is used as a hint for humans, not as
     * an information for algorithms.
     */
    public function isAutoreply(): bool
    {
        $email = $this->getEmail();

        $headerChecks = [
            'Auto-Submitted' => fn (string $value): bool => $value !== 'no',
            'X-Autoreply' => fn (string $value): bool => $value === 'yes',
            'X-Autorespond' => fn (string $value): bool => $value !== '',
            'X-Autoresponder' => fn (string $value): bool => $value !== '',
            'Precedence' => fn (string $value): bool => $value === 'auto_reply',
            'X-Precedence' => fn (string $value): bool => $value === 'auto_reply',
            'Delivered-To' => fn (string $value): bool => $value === 'autoresponder',
        ];

        foreach ($headerChecks as $headerName => $headerCheck) {
            $header = $email->get($headerName);
            if (!$header instanceof PHPIMAP\Attribute) {
                continue;
            }

            $value = $header->first() ?? '';
            $value = strtolower($value);
            if ($value && $headerCheck($value)) {
                return true;
            }
        }

        return false;
    }

    public function getSubject(): string
    {
        return $this->getEmail()->getSubject();
    }

    public function getBody(): string
    {
        $email = $this->getEmail();
        if ($email->hasHTMLBody()) {
            return $email->getHTMLBody();
        } else {
            $messageContent = $email->getTextBody();
            $messageContent = htmlspecialchars($messageContent, ENT_COMPAT, 'UTF-8');
            $messageContent = nl2br($messageContent);
            return $messageContent;
        }
    }

    /**
     * @return PHPIMAP\Attachment[]
     */
    public function getAttachments(): array
    {
        $email = $this->getEmail();
        return $email->getAttachments()->toArray();
    }

    public function getDate(): \DateTimeImmutable
    {
        $date = $this->getEmail()->getDate()->first();
        return $date->toDateTimeImmutable();
    }

    public function extractTicketId(): ?int
    {
        preg_match('/\[#(?P<id>\d+)\]/', $this->getSubject(), $matches);

        if (isset($matches['id'])) {
            return intval($matches['id']);
        } else {
            return null;
        }
    }
}

src/Controller/MailboxesController.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Controller;

use App\Entity;
use App\Form;
use App\Message;
use App\Repository;
use App\Service;
use App\Utils;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Messenger\Stamp\TransportNamesStamp;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatableMessage;
use Symfony\Contracts\Translation\TranslatorInterface;

class MailboxesController extends BaseController
{
    #[Route('/mailboxes', name: 'mailboxes', methods: ['GET', 'HEAD'])]
    public function index(
        Repository\MailboxRepository $mailboxRepository,
        Repository\MailboxEmailRepository $mailboxEmailRepository,
        Service\Sorter\MailboxSorter $mailboxSorter,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:mailboxes');

        $mailboxes = $mailboxRepository->findAll();
        $mailboxSorter->sort($mailboxes);

        $errorMailboxEmails = $mailboxEmailRepository->findInError();

        return $this->render('mailboxes/index.html.twig', [
            'mailboxes' => $mailboxes,
            'errorMailboxEmails' => $errorMailboxEmails,
        ]);
    }

    #[Route('/mailboxes/new', name: 'new mailbox')]
    public function new(
        Request $request,
        Repository\MailboxRepository $mailboxRepository,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:mailboxes');

        $mailbox = new Entity\Mailbox();
        $form = $this->createNamedForm('mailbox', Form\MailboxForm::class, $mailbox);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mailbox = $form->getData();
            $mailboxRepository->save($mailbox, true);

            return $this->redirectToRoute('mailboxes');
        }

        return $this->render('mailboxes/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/mailboxes/{uid:mailbox}/edit', name: 'edit mailbox')]
    public function edit(
        Entity\Mailbox $mailbox,
        Request $request,
        Repository\MailboxRepository $mailboxRepository,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:mailboxes');

        $form = $this->createNamedForm('mailbox', Form\MailboxForm::class, $mailbox);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mailbox = $form->getData();
            $mailbox->resetLastError();
            $mailboxRepository->save($mailbox, true);

            $this->addFlash('success', new TranslatableMessage('notifications.saved'));

            return $this->redirectToRoute('edit mailbox', [
                'uid' => $mailbox->getUid(),
            ]);
        }

        return $this->render('mailboxes/edit.html.twig', [
            'mailbox' => $mailbox,
            'form' => $form,
        ]);
    }

    #[Route('/mailboxes/{uid:mailbox}/test', name: 'test mailbox', methods: ['POST'])]
    public function test(
        Request $request,
        Entity\Mailbox $mailbox,
        Repository\MailboxRepository $mailboxRepository,
        TranslatorInterface $translator,
        Service\MailboxService $mailboxService,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:mailboxes');

        /** @var string $csrfToken */
        $csrfToken = $request->request->get('_csrf_token', '');

        if (!$this->isCsrfTokenValid('test mailbox', $csrfToken)) {
            $this->addFlash('error', $translator->trans('csrf.invalid', [], 'errors'));
            return $this->redirectToRoute('mailboxes');
        }

        $client = $mailboxService->getClient($mailbox);

        try {
            $client->connect();
            $client->disconnect();

            $mailbox->setLastError('');
            $mailboxRepository->save($mailbox, true);

            $this->addFlash('success', new TranslatableMessage('mailboxes.test.success'));
        } catch (\Exception $e) {
            $error = $e->getMessage();

            $mailbox->setLastError($error);
            $mailboxRepository->save($mailbox, true);
        }

        return $this->redirectToRoute('edit mailbox', [
            'uid' => $mailbox->getUid(),
        ]);
    }

    #[Route('/mailboxes/collect', name: 'collect mailboxes', methods: ['POST'])]
    public function collect(
        Request $request,
        TranslatorInterface $translator,
        MessageBusInterface $bus,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:mailboxes');

        /** @var string $csrfToken */
        $csrfToken = $request->request->get('_csrf_token', '');

        if (!$this->isCsrfTokenValid('collect mailboxes', $csrfToken)) {
            $this->addFlash('error', $translator->trans('csrf.invalid', [], 'errors'));
            return $this->redirectToRoute('mailboxes');
        }

        $bus->dispatch(new Message\FetchMailboxes(), [
            new TransportNamesStamp('sync'),
        ]);
        $bus->dispatch(new Message\CreateTicketsFromMailboxEmails(), [
            new TransportNamesStamp('sync'),
        ]);

        return $this->redirectToRoute('mailboxes');
    }

    #[Route('/mailboxes/{uid:mailbox}/deletion', name: 'delete mailbox', methods: ['POST'])]
    public function delete(
        Entity\Mailbox $mailbox,
        Request $request,
        Repository\MailboxRepository $mailboxRepository,
        TranslatorInterface $translator,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:mailboxes');

        /** @var \App\Entity\User $user */
        $user = $this->getUser();

        /** @var string $csrfToken */
        $csrfToken = $request->request->get('_csrf_token', '');

        if (!$this->isCsrfTokenValid('delete mailbox', $csrfToken)) {
            $this->addFlash('error', $translator->trans('csrf.invalid', [], 'errors'));
            return $this->redirectToRoute('edit mailbox', [
                'uid' => $mailbox->getUid(),
            ]);
        }

        $mailboxRepository->remove($mailbox, true);

        return $this->redirectToRoute('mailboxes');
    }
}

templates/mailboxes/_form.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.name) }}

    <div class="cols cols--center cols--always flow flow--small">
        <div class="col--size8">
            {{ form_row(form.host) }}
        </div>

        <div class="col--size4">
            {{ form_row(form.port) }}
        </div>
    </div>

    {{ form_row(form.encryption) }}

    {{ form_row(form.username) }}

    {{ form_row(form.plainPassword) }}

    {{ form_row(form.folder) }}

    {{ form_row(form.postAction) }}

    {{ form_row(form.submit) }}
{{ form_end(form) }}

templates/mailboxes/edit.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'mailboxes' %}

{% block title %}{{ 'mailboxes.edit.title' | trans }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <a href="{{ path('mailboxes') }}">
            {{ 'mailboxes.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ 'mailboxes.edit.title' | trans }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <h1>{{ 'mailboxes.edit.title' | trans }}</h1>

        <div class="panel flow">
            <form method="POST" action="{{ path('test mailbox', { uid: mailbox.uid }) }}" class="text--right">
                <input type="hidden" name="_csrf_token" value="{{ csrf_token('test mailbox') }}">
                <button type="submit">
                    {{ 'mailboxes.edit.test_mailbox' | trans }}
                </button>
            </form>

            {% if mailbox.lastError %}
                <div class="wrapper wrapper--small wrapper--center">
                    {{ include('alerts/_error.html.twig', { message: mailbox.lastError }, with_context = false) }}
                </div>
            {% endif %}

            {{ include('mailboxes/_form.html.twig', { form: form }) }}
        </div>

        <div class="panel">
            <form action="{{ path('delete mailbox', { uid: mailbox.uid }) }}" method="post" class="form--standard">
                <h2>{{ 'mailboxes.deletion.title' | trans }}</h2>

                {{ include('alerts/_alert.html.twig', {
                    type: 'warning',
                    title: 'common.caution' | trans,
                    message: 'mailboxes.deletion.going_delete' | trans({ mailbox: mailbox.name }),
                }, with_context = false) }}

                {% if error %}
                    {{ include('alerts/_error.html.twig', { message: error }, with_context = false) }}
                {% endif %}

                <div class="form__actions">
                    <button
                        class="button--primary"
                        type="submit"
                        data-turbo-confirm="{{ 'mailboxes.deletion.confirm' | trans }}"
                    >
                        {{ 'mailboxes.deletion.submit' | trans }}
                    </button>
                </div>

                <input type="hidden" name="_csrf_token" value="{{ csrf_token('delete mailbox') }}">
            </form>
        </div>
    </main>
{% endblock %}

templates/mailboxes/index.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'mailboxes' %}

{% block title %}{{ 'mailboxes.index.title' | trans }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ 'mailboxes.index.title' | trans }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <h1>{{ 'mailboxes.index.title' | trans }}</h1>

        <div class="flow">
            <div class="cols flow">
                <div class="col--extend cols cols--center flow">
                    {% if mailboxes|length > 0 %}
                        <p class="text--secondary">
                            {{ 'mailboxes.index.number' | trans({ count: mailboxes|length }) }}
                        </p>

                        <form method="POST" action="{{ path('collect mailboxes') }}">
                            <input type="hidden" name="_csrf_token" value="{{ csrf_token('collect mailboxes') }}">
                            <button type="submit">
                                {{ 'mailboxes.index.collect' | trans }}
                            </button>
                        </form>
                    {% endif %}
                </div>

                <a href="{{ path('new mailbox') }}" class="button button--primary button--uppercase">
                    {{ icon('plus') }}
                    {{ 'mailboxes.index.new_mailbox' | trans }}
                </a>
            </div>

            {% if mailboxes|length > 0 %}
                <ul class="list--padded list--border list--nostyle">
                    {% for mailbox in mailboxes %}
                        <li class="cols flow flow--small" data-test="mailbox-item">
                            <span class="col--extend">
                                {% if mailbox.lastError %}
                                    <span class="text--error">
                                        {{ icon('circle-exclamation-error') }}
                                        {{ mailbox.name }}
                                        {{ 'mailboxes.index.error' | trans }}
                                    </span>
                                {% else %}
                                    {{ mailbox.name }}
                                {% endif %}
                            </span>

                            <a href="{{ path('edit mailbox', { uid: mailbox.uid }) }}">
                                {{ 'mailboxes.index.edit' | trans }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="placeholder flow flow--larger">
                    <img class="placeholder__image" src="{{ asset('illustration-placeholder.svg') }}" alt="" />

                    <p class="placeholder__text">
                        {{ 'mailboxes.index.none' | trans }}
                    </p>
                </div>
            {% endif %}

            {% if errorMailboxEmails %}
                <h2>{{ 'mailboxes.index.emails.title' | trans }}</h2>

                <p class="text--secondary">
                    {{ 'mailboxes.index.emails.desc' | trans }}
                </p>

                <ul class="list--padded list--border list--nostyle">
                    {% for mailboxEmail in errorMailboxEmails %}
                        <li class="flow" data-test="mailbox-email-item">
                            <div class="cols flow">
                                <span class="col--extend">
                                    {{ mailboxEmail.subject }}
                                </span>

                                <span class="text--secondary text--small">
                                    {{ mailboxEmail.from }}
                                </span>

                                <span class="text--secondary text--small">
                                    <time datetime="{{ mailboxEmail.date | dateIso }}">
                                        {{ mailboxEmail.date | dateTrans }}
                                    </time>
                                </span>
                            </div>

                            <div class="cols flow">
                                <div class="col--extend">
                                    {% if mailboxEmail.lastErrorSummary == mailboxEmail.lastError %}
                                        <p class="text--error text--bold">
                                            {{ 'mailboxes.index.emails.error' | trans }}
                                            {{ mailboxEmail.lastError }}
                                        </p>
                                    {% else %}
                                        <details>
                                            <summary class="text--error text--bold">
                                                {{ 'mailboxes.index.emails.error' | trans }}
                                                {{ mailboxEmail.lastErrorSummary }}
                                            </summary>

                                            <pre class="pre--formatted">{{ mailboxEmail.lastError }}</pre>
                                        </details>
                                    {% endif %}
                                </div>

                                <form method="POST" action="{{ path('delete mailbox email', { uid: mailboxEmail.uid }) }}">
                                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('delete mailbox email') }}">
                                    <button
                                        type="submit"
                                        class="button--anchor"
                                        data-turbo-confirm="{{ 'mailboxes.index.emails.delete.confirm' | trans }}"
                                    >
                                        {{ 'mailboxes.index.emails.delete' | trans }}
                                    </button>
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </main>
{% endblock %}

templates/mailboxes/new.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'mailboxes' %}

{% block title %}{{ 'mailboxes.new.title' | trans }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <a href="{{ path('mailboxes') }}">
            {{ 'mailboxes.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ 'mailboxes.new.title' | trans }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <h1>{{ 'mailboxes.new.title' | trans }}</h1>

        <div class="panel">
            {{ include('mailboxes/_form.html.twig', { form: form }) }}
        </div>
    </main>
{% endblock %}