src/Entity/User.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Entity;

use App\ActivityMonitor\MonitorableEntityInterface;
use App\ActivityMonitor\MonitorableEntityTrait;
use App\Repository\UserRepository;
use App\Service;
use App\Uid\UidEntityInterface;
use App\Uid\UidEntityTrait;
use App\Utils;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Mime\Address;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Translation\TranslatableMessage;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`users`')]
#[UniqueEntity(
    fields: 'email',
    message: new TranslatableMessage('user.email.already_used', [], 'errors'),
)]
class User implements
    EntityInterface,
    UserInterface,
    PasswordAuthenticatedUserInterface,
    MonitorableEntityInterface,
    UidEntityInterface
{
    use MonitorableEntityTrait;
    use UidEntityTrait;

    public const NAME_MAX_LENGTH = 100;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20, unique: true)]
    private ?string $uid = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $createdBy = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?User $updatedBy = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Assert\NotBlank(
        message: new TranslatableMessage('user.email.required', [], 'errors'),
    )]
    #[Assert\Email(
        message: new TranslatableMessage('user.email.invalid', [], 'errors'),
    )]
    private ?string $email = null;

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, options: ['default' => 'auto'])]
    #[Assert\NotBlank(
        message: new TranslatableMessage('user.color_scheme.required', [], 'errors'),
    )]
    #[Assert\Choice(
        choices: ['auto', 'light', 'dark'],
        message: new TranslatableMessage('user.color_scheme.invalid', [], 'errors'),
    )]
    private ?string $colorScheme = 'auto';

    #[ORM\Column(length: 5, options: ['default' => 'en_GB'])]
    #[Assert\NotBlank(
        message: new TranslatableMessage('user.language.required', [], 'errors'),
    )]
    #[Assert\Choice(
        callback: [Service\Locales::class, 'getSupportedLocalesCodes'],
        message: new TranslatableMessage('user.language.invalid', [], 'errors'),
    )]
    private ?string $locale = null;

    #[ORM\Column(length: self::NAME_MAX_LENGTH, nullable: true)]
    #[Assert\Length(
        max: self::NAME_MAX_LENGTH,
        maxMessage: new TranslatableMessage('user.name.max_chars', [], 'errors'),
    )]
    private ?string $name = null;

    /** @var Collection<int, Authorization> $authorizations */
    #[ORM\OneToMany(
        mappedBy: 'holder',
        targetEntity: Authorization::class,
        orphanRemoval: true,
        cascade: ['persist'],
    )]
    private Collection $authorizations;

    #[ORM\Column]
    private ?bool $hideEvents = false;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?Organization $organization = null;

    #[ORM\Column(length: 255, options: ['default' => ''])]
    private ?string $ldapIdentifier = null;

    /** @var Collection<int, Team> */
    #[ORM\ManyToMany(targetEntity: Team::class, mappedBy: 'agents')]
    private Collection $teams;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?Token $resetPasswordToken = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $loginDisabledAt = null;

    #[ORM\Column(type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $anonymizedAt = null;

    #[ORM\ManyToOne(targetEntity: self::class)]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private ?self $anonymizedBy = null;

    public function __construct()
    {
        $this->name = '';
        $this->email = '';
        $this->password = '';
        $this->locale = '';
        $this->ldapIdentifier = '';
        $this->authorizations = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function getEmailAddress(): Address
    {
        $email = $this->getEmail();
        $name = $this->getDisplayName();

        if ($email === $name) {
            return new Address($email);
        } else {
            return new Address($email, $name);
        }
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     *
     * @return non-empty-string
     */
    public function getUserIdentifier(): string
    {
        $identifier = $this->email;

        if (!$identifier) {
            throw new \LogicException('User identifier (email) cannot be empty');
        }

        return $identifier;
    }

    /**
     * This methods has nothing to do with "Bileto roles". It is in fact a
     * requirement of the Symfony authentication system.
     *
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getColorScheme(): ?string
    {
        return $this->colorScheme;
    }

    public function setColorScheme(string $colorScheme): self
    {
        $this->colorScheme = $colorScheme;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        if ($this->name) {
            return $this->name;
        } else {
            return $this->email;
        }
    }

    /**
     * @return Collection<int, Authorization>
     */
    public function getAuthorizations(): Collection
    {
        return $this->authorizations;
    }

    public function addAuthorization(Authorization $authorization): static
    {
        if (!$this->authorizations->contains($authorization)) {
            $this->authorizations->add($authorization);
            $authorization->setHolder($this);
        }

        return $this;
    }

    public function areEventsHidden(): ?bool
    {
        return $this->hideEvents;
    }

    public function setHideEvents(bool $hideEvents): self
    {
        $this->hideEvents = $hideEvents;

        return $this;
    }

    public function getOrganization(): ?Organization
    {
        return $this->organization;
    }

    public function setOrganization(?Organization $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    public function getLdapIdentifier(): ?string
    {
        return $this->ldapIdentifier;
    }

    public function setLdapIdentifier(?string $ldapIdentifier): static
    {
        $this->ldapIdentifier = $ldapIdentifier;

        return $this;
    }

    /**
     * @return 'local'|'ldap'
     */
    public function getAuthType(): string
    {
        if ($this->getLdapIdentifier() === '') {
            return 'local';
        } else {
            return 'ldap';
        }
    }

    /**
     * @return Collection<int, Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function getResetPasswordToken(): ?Token
    {
        return $this->resetPasswordToken;
    }

    public function setResetPasswordToken(?Token $resetPasswordToken): static
    {
        $this->resetPasswordToken = $resetPasswordToken;

        return $this;
    }

    public function canLogin(): bool
    {
        return $this->loginDisabledAt === null;
    }

    public function allowLogin(): static
    {
        $this->loginDisabledAt = null;

        return $this;
    }

    public function disableLogin(): static
    {
        if (!$this->loginDisabledAt) {
            $this->loginDisabledAt = Utils\Time::now();
            $this->password = Utils\Random::hex(64);
        }

        return $this;
    }

    public function setLoginDisabledAt(?\DateTimeImmutable $loginDisabledAt): static
    {
        $this->loginDisabledAt = $loginDisabledAt;

        return $this;
    }

    public function isAnonymized(): bool
    {
        return $this->anonymizedAt !== null;
    }

    public function anonymize(string $name, self $by): static
    {
        $this->disableLogin();

        $this->name = $name;
        $this->email = "anonymous+{$this->uid}@example.com";

src/Controller/Teams/AgentsController.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Controller\Teams;

use App\Controller\BaseController;
use App\Entity\Team;
use App\Entity\User;
use App\Repository\UserRepository;
use App\Service\ActorsLister;
use App\Service\TeamService;
use App\Service\UserCreator;
use App\Service\UserCreatorException;
use App\Utils\ConstraintErrorsFormatter;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class AgentsController extends BaseController
{
    #[Route('/teams/{uid:team}/agents/new', name: 'new team agent', methods: ['GET', 'HEAD'])]
    public function new(
        Team $team,
        ActorsLister $actorsLister,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:agents');

        $agents = $actorsLister->findAll('agent');
        $agents = array_filter($agents, function (User $agent) use ($team): bool {
            return !$team->hasAgent($agent);
        });

        return $this->render('teams/agents/new.html.twig', [
            'team' => $team,
            'agents' => $agents,
            'agentEmail' => '',
        ]);
    }

    #[Route('/teams/{uid:team}/agents/new', name: 'add team agent', methods: ['POST'])]
    public function add(
        Team $team,
        Request $request,
        UserRepository $userRepository,
        UserCreator $userCreator,
        TeamService $teamService,
        ActorsLister $actorsLister,
        TranslatorInterface $translator,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:agents');

        /** @var \App\Entity\User */
        $currentUser = $this->getUser();

        /** @var string */
        $agentEmail = $request->request->get('agentEmail', '');

        /** @var string */
        $csrfToken = $request->request->get('_csrf_token', '');

        $agents = $actorsLister->findAll('agent');
        $agents = array_filter($agents, function (User $agent) use ($team): bool {
            return !$team->hasAgent($agent);
        });

        if (!$this->isCsrfTokenValid('add team agent', $csrfToken)) {
            return $this->renderBadRequest('teams/agents/new.html.twig', [
                'team' => $team,
                'agents' => $agents,
                'agentEmail' => $agentEmail,
                'error' => $translator->trans('csrf.invalid', [], 'errors'),
            ]);
        }

        $agent = $userRepository->findOneBy([
            'email' => $agentEmail,
        ]);

        if (!$agent) {
            try {
                $agent = $userCreator->create(
                    email: $agentEmail,
                    locale: $currentUser->getLocale(),
                );
            } catch (UserCreatorException $e) {
                return $this->renderBadRequest('teams/agents/new.html.twig', [
                    'team' => $team,
                    'agents' => $agents,
                    'agentEmail' => $agentEmail,
                    'errors' => ConstraintErrorsFormatter::format($e->getErrors()),
                ]);
            }
        }

        $teamService->addAgent($team, $agent);

        return $this->redirectToRoute('team', [
            'uid' => $team->getUid(),
        ]);
    }

    #[Route('/teams/{uid:team}/agents/deletion', name: 'remove team agent', methods: ['POST'])]
    public function remove(
        Team $team,
        Request $request,
        UserRepository $userRepository,
        TeamService $teamService,
        TranslatorInterface $translator,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:agents');

        /** @var string */
        $agentUid = $request->request->get('agentUid', '');

        /** @var string */
        $csrfToken = $request->request->get('_csrf_token', '');

        if (!$this->isCsrfTokenValid('remove team agent', $csrfToken)) {
            $this->addFlash('error', $translator->trans('csrf.invalid', [], 'errors'));

            return $this->redirectToRoute('team', [
                'uid' => $team->getUid(),
            ]);
        }

        $agent = $userRepository->findOneBy(['uid' => $agentUid]);
        if ($agent) {
            $teamService->removeAgent($team, $agent);
        }

        return $this->redirectToRoute('team', [
            'uid' => $team->getUid(),
        ]);
    }
}

src/Controller/Teams/AuthorizationsController.php
<?php

// This file is part of Bileto.
// Copyright 2022-2026 Probesys
// SPDX-License-Identifier: AGPL-3.0-or-later

namespace App\Controller\Teams;

use App\Controller\BaseController;
use App\Entity;
use App\Form;
use App\Service;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class AuthorizationsController extends BaseController
{
    #[Route('/teams/{uid:team}/authorizations/new', name: 'new team authorization')]
    public function new(
        Entity\Team $team,
        Request $request,
        Service\TeamService $teamService,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:agents');

        $teamAuthorization = new Entity\TeamAuthorization();
        $teamAuthorization->setTeam($team);

        $form = $this->createNamedForm('authorization', Form\Team\AuthorizationForm::class, $teamAuthorization);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $teamAuthorization = $form->getData();
            $teamService->createAuthorization($teamAuthorization);

            return $this->redirectToRoute('team', [
                'uid' => $team->getUid(),
            ]);
        }

        return $this->render('teams/authorizations/new.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route(
        '/team-authorizations/{uid:teamAuthorization}/deletion',
        name: 'delete team authorization',
        methods: ['POST']
    )]
    public function delete(
        Entity\TeamAuthorization $teamAuthorization,
        Request $request,
        Service\TeamService $teamService,
        TranslatorInterface $translator,
    ): Response {
        $this->denyAccessUnlessGranted('admin:manage:agents');

        /** @var string $csrfToken */
        $csrfToken = $request->request->get('_csrf_token', '');

        $team = $teamAuthorization->getTeam();

        if (!$this->isCsrfTokenValid('delete team authorization', $csrfToken)) {
            $this->addFlash('error', $translator->trans('csrf.invalid', [], 'errors'));
            return $this->redirectToRoute('team', [
                'uid' => $team->getUid(),
            ]);
        }

        $teamService->removeAuthorization($teamAuthorization);

        return $this->redirectToRoute('team', [
            'uid' => $team->getUid(),
        ]);
    }
}

templates/teams/edit.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'teams' %}

{% block title %}{{ 'teams.edit.title' | trans }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <a href="{{ path('teams') }}">
            {{ 'teams.index.title' | trans }}
        </a>

        <a href="{{ path('team', { uid: team.uid }) }}">
            {{ team.name }}
        </a>

        <span aria-current="page">
            {{ 'teams.edit.title' | trans }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <h1>{{ 'teams.edit.title' | trans }}</h1>

        <div class="panel">
            {{ form(form) }}
        </div>

        <div class="panel">
            <form action="{{ path('delete team', { uid: team.uid }) }}" method="post" class="form--standard">
                <h2>{{ 'teams.deletion.title' | trans }}</h2>

                {{ include('alerts/_alert.html.twig', {
                    type: 'warning',
                    title: 'common.caution' | trans,
                    message: 'teams.deletion.going_delete' | trans({ team: team.name }),
                }, with_context = false) }}

                {% if error %}
                    {{ include('alerts/_error.html.twig', { message: error }, with_context = false) }}
                {% endif %}

                <div class="form__actions">
                    <button
                        class="button--primary"
                        type="submit"
                        data-turbo-confirm="{{ 'teams.deletion.confirm' | trans }}"
                    >
                        {{ 'teams.deletion.submit' | trans }}
                    </button>
                </div>

                <input type="hidden" name="_csrf_token" value="{{ csrf_token('delete team') }}">
            </form>
        </div>
    </main>
{% endblock %}

templates/teams/index.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'teams' %}

{% block title %}{{ 'teams.index.title' | trans }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ 'teams.index.title' | trans }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body teams-index">
        <h1>{{ 'teams.index.title' | trans }}</h1>

        <div class="flow">
            <div class="cols cols--center flow">
                <div class="col--extend">
                    {% if teams|length > 0 %}
                        <p class="text--secondary">
                            {{ 'teams.index.number' | trans({ count: teams|length }) }}
                        </p>
                    {% endif %}
                </div>

                <a href="{{ path('new team') }}" class="button button--primary button--uppercase">
                    {{ icon('plus') }}
                    {{ 'teams.index.new_team' | trans }}
                </a>
            </div>

            {% if teams|length > 0 %}
                <ul class="list--padded list--border list--nostyle">
                    {% for team in teams %}
                        <li class="cols cols--center flow flow--small" data-test="team-item">
                            <span class="col--extend list__item-title">
                                <a href="{{ path('team', { uid: team.uid }) }}">
                                    {{ team.name }}
                                </a>
                            </span>

                            <span class="col--noshrink">
                                <span class="badge badge--grey">
                                    {{ 'teams.index.agents' | trans({ count: team.agents|length }) }}
                                </span>

                                <span class="badge badge--grey">
                                    {{ 'teams.index.authorizations' | trans({ count: team.teamAuthorizations|length }) }}
                                </span>
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="placeholder flow flow--larger">
                    <img class="placeholder__image" src="{{ asset('illustration-placeholder.svg') }}" alt="" />

                    <p class="placeholder__text">
                        {{ 'teams.index.none' | trans }}
                    </p>
                </div>
            {% endif %}
        </div>
    </main>
{% endblock %}

templates/teams/new.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'teams' %}

{% block title %}{{ 'teams.new.title' | trans }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <a href="{{ path('teams') }}">
            {{ 'teams.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ 'teams.new.title' | trans }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <h1>{{ 'teams.new.title' | trans }}</h1>

        <div class="panel">
            {{ form(form) }}
        </div>
    </main>
{% endblock %}

templates/teams/show.html.twig
{#
 # This file is part of Bileto.
 # Copyright 2022-2026 Probesys
 # SPDX-License-Identifier: AGPL-3.0-or-later
 #}

{% extends 'admin.html.twig' %}

{% set currentMenu = 'teams' %}

{% block title %}{{ team.name }}{% endblock %}

{% block breadcrumb %}
    <nav class="layout__breadcrumb" aria-label="{{ 'layout.breadcrumb' | trans }}">
        <a href="{{ path('home') }}">
            {{ 'layout.home' | trans }}
        </a>

        <a href="{{ path('admin') }}">
            {{ 'admin.index.title' | trans }}
        </a>

        <a href="{{ path('teams') }}">
            {{ 'teams.index.title' | trans }}
        </a>

        <span aria-current="page">
            {{ team.name }}
        </span>
    </nav>
{% endblock %}

{% block body %}
    <main class="layout__body">
        <div class="flow flow--smaller">
            <h1>{{ team.name }}</h1>

            {% if team.isResponsible %}
                <p class="text--center">
                    {{ 'teams.show.team_responsible' | trans }}
                </p>
            {% endif %}

            <div class="text--right">
                <details
                    class="popup"
                    data-controller="popup"
                    data-action="toggle->popup#update click@window->popup#closeOnClickOutside"
                >
                    <summary class="popup__opener">
                        <span class="button button--discreet">
                            {{ 'common.actions' | trans }}
                            {{ icon('angle-down') }}
                        </span>
                    </summary>

                    <nav class="popup__container popup__container--right">
                        <a class="popup__item" href="{{ path('edit team', { uid: team.uid }) }}">
                            {{ 'teams.show.edit' | trans }}
                        </a>
                    </nav>
                </details>
            </div>
        </div>

        <div class="flow">
            <h2 class="sr-only">{{ 'teams.show.agents.title' | trans }}</h2>

            <div class="cols cols--center flow">
                <div class="col--extend">
                    {% if agents|length > 0 %}
                        <p class="text--secondary">
                            {{ 'teams.show.agents.number' | trans({ count: agents|length }) }}
                        </p>
                    {% endif %}
                </div>

                <a href="{{ path('new team agent', { uid: team.uid }) }}" class="button button--primary button--uppercase">
                    {{ icon('plus') }}
                    {{ 'teams.show.agents.new' | trans }}
                </a>
            </div>

            {% if agents|length > 0 %}
                <ul class="list--padded list--border list--nostyle">
                    {% for user in agents %}
                        <li class="cols cols--center flow flow--small" data-test="user-item">
                            <span class="col--extend">
                                <span class="list__item-title">
                                    {{ user.displayName }}

                                    {% if user == app.user %}
                                        ({{ 'users.yourself' | trans }})
                                    {% endif %}
                                </span>

                                {% if user.name %}
                                    <span class="text--secondary text--small">
                                        {{ user.email }}
                                    </span>
                                {% endif %}
                            </span>

                            <div class="col--noshrink cols cols--always cols--center flow flow--small">
                                <form method="post" action="{{ path('remove team agent', { uid: team.uid }) }}">
                                    <input type="hidden" name="agentUid" value="{{ user.uid }}" />
                                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('remove team agent') }}">

                                    <button
                                        class="button--discreet"
                                        type="submit"
                                        data-turbo-confirm="{{ 'teams.show.agents.remove.confirm' | trans }}"
                                    >
                                        {{ 'teams.show.agents.remove' | trans }}
                                    </button>
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="placeholder flow flow--larger">
                    <img class="placeholder__image" src="{{ asset('illustration-placeholder.svg') }}" alt="" />

                    <p class="placeholder__text">
                        {{ 'teams.show.agents.none' | trans }}
                    </p>
                </div>
            {% endif %}
        </div>

        <div class="panel flow">
            <div class="cols cols--center flow">
                <h2 class="col--extend">{{ 'teams.show.authorizations.title' | trans }}</h2>

                <a class="button button--primary button--uppercase" href="{{ path('new team authorization', { uid: team.uid }) }}">
                    {{ icon('plus') }}
                    {{ 'teams.show.authorizations.new' | trans }}
                </a>
            </div>

            {% if teamAuthorizations %}
                <div class="grid">
                    {% for authorization in teamAuthorizations %}
                        {{ include('authorizations/_authorization.html.twig', {
                            authorization: authorization,
                            mode: 'team',
                        }, with_context = false) }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </main>
{% endblock %}